# Generated by Django 2.2.3 on 2019-07-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('path', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('state', models.TextField()),
            ],
        ),
    ]
