# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortfolio', '0007_backtestdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliomodel',
            name='stopLoss',
            field=models.FloatField(null=True, verbose_name=b'Stop Loss'),
        ),
    ]
