# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortfolio', '0008_userportfoliomodel_stoploss'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactionsmodel',
            name='returns',
            field=models.FloatField(null=True),
        ),
    ]
