# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortfolio', '0009_usertransactionsmodel_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactionsmodel',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
