# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortfolio', '0010_usertransactionsmodel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliomodel',
            name='stopTarget',
            field=models.FloatField(null=True, verbose_name=b'Target'),
        ),
    ]
