# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-16 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortfolio', '0011_userportfoliomodel_stoptarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliomodel',
            name='minStopLoss',
            field=models.FloatField(null=True, verbose_name=b'Min Stop Loss'),
        ),
    ]
