# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortfolio', '0012_userportfoliomodel_minstoploss'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDForexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.TextField(unique=True)),
            ],
        ),
    ]
